#!/usr/bin/env bash
# provision-test-db.sh — stand up bion_test on the SAME dedicated cluster as bion (directive-23
# Part A), so `vitest run` never writes to the real bion database.
#
# Reuses the cluster (127.0.0.1:5433) and the existing bion_owner/bion_rw roles + passwords
# generated by provision-db.sh (~/.bion-pg/.ownerpw, .rwpw) — no new roles, no new cluster.
# Idempotent: safe to re-run.
set -euo pipefail

PGBIN="${BION_PGBIN:-/c/Program Files/PostgreSQL/16/bin}"
PGPORT="${BION_PGPORT:-5433}"
SECRETS_DIR="$HOME/.bion-pg"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

[ -f "$SECRETS_DIR/.superpw" ] || { echo "[provision-test-db] no cluster found — run db:provision first" >&2; exit 1; }
[ -f "$SECRETS_DIR/.ownerpw" ] || { echo "[provision-test-db] bion_owner role not provisioned — run db:provision first" >&2; exit 1; }
[ -f "$SECRETS_DIR/.rwpw" ]    || { echo "[provision-test-db] bion_rw role not provisioned — run db:provision first" >&2; exit 1; }

psql_super() { PGPASSWORD="$(cat "$SECRETS_DIR/.superpw")" "$PGBIN/psql" -h 127.0.0.1 -p "$PGPORT" -U bion_super -w "$@"; }

if ! "$PGBIN/pg_isready" -h 127.0.0.1 -p "$PGPORT" -q; then
  echo "[provision-test-db] cluster not running on 127.0.0.1:$PGPORT — run db:start first" >&2
  exit 1
fi

# 1) database (created by bion_super so we can re-home it below; idempotent)
psql_super -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='bion_test'" | grep -q 1 \
  || PGPASSWORD="$(cat "$SECRETS_DIR/.superpw")" "$PGBIN/createdb" -h 127.0.0.1 -p "$PGPORT" -U bion_super -w -O bion_super bion_test

# 2) db-scoped grants + ownership — same shape as provision-db.sh step 5, targeting bion_test
psql_super -d bion_test -q <<'SQL'
REVOKE ALL ON DATABASE bion_test FROM PUBLIC;
GRANT CONNECT ON DATABASE bion_test TO bion_owner, bion_rw;
ALTER SCHEMA public OWNER TO bion_owner;
REVOKE CREATE ON SCHEMA public FROM bion_rw;
GRANT USAGE ON SCHEMA public TO bion_rw;
SQL

# 3) write repo-root .env.test (gitignored) — same roles/passwords as .env.local, different database
OWNERPW="$(cat "$SECRETS_DIR/.ownerpw")"; RWPW="$(cat "$SECRETS_DIR/.rwpw")"
cat > "$REPO_ROOT/.env.test" <<EOF
# Bion test env — GITIGNORED. Same cluster/roles as .env.local, isolated database (directive-23).
BION_DATABASE_URL=postgresql://bion_rw:${RWPW}@127.0.0.1:${PGPORT}/bion_test
BION_MIGRATE_URL=postgresql://bion_owner:${OWNERPW}@127.0.0.1:${PGPORT}/bion_test
BION_NTFY_URL=
BION_NTFY_TOKEN=
EOF

echo "[provision-test-db] done. cluster 127.0.0.1:$PGPORT, db bion_test, roles bion_owner/bion_rw. .env.test written."
echo "[provision-test-db] next: pnpm test (globalSetup migrates bion_test automatically)"
