// Bion — coordination primitives (spec §3.3) + state helpers.
export { record } from './core/record.js'
export { send } from './core/send.js'
export { recordEvent } from './core/events.js'
export { queryState } from './core/queryState.js'
export { handoff } from './core/handoff.js'
export { createTask, getTask, setTaskStatus } from './core/tasks.js'
export { listInvariants, listFdqs, getAgent } from './core/ledgers.js'
export { findUnconsumedByHash, consume, isConsumed } from './core/consumption.js'
export { routePacket } from './core/routing.js'
export type { RouteInput, RouteResult } from './core/routing.js'
export { enqueueOutbox, drainOutbox, repairPublishes, reconcile, notifyDurably } from './db/outbox.js'
export type { OutboxKind, OutboxRow, PublishPayload, DrainDeps, DrainResult } from './db/outbox.js'
export { stageCompletion } from './loop/monitor.js'
export { assertAcyclic, findCycle, CycleError } from './core/dag.js'
export { sha256, dedupKey, newId } from './core/ids.js'
export { writePacket, stagePacket, publishStaged, discardStaged, publishBodyToPath, readPacket, listBox, movePacket, mailboxRoot } from './mailbox/mailbox.js'
export type { StagedPacket, WrittenPacket } from './mailbox/mailbox.js'
export { BaseAdapter } from './adapters/baseAdapter.js'
export { DesktopAdapter } from './adapters/desktop.js'
export { KovAdapter } from './adapters/kov.js'
export type { AgentAdapter, Packet, DispatchResult, ConsumedPacket, PollResult, FlaggedPacket } from './adapters/types.js'
export { selectDispatchable, dispatchNext } from './loop/dispatcher.js'
export { reportCompletion } from './loop/monitor.js'
export type { CompletionDeps, CompletionOutcome, NotifyFn } from './loop/monitor.js'
export type { DispatchOutcome } from './loop/dispatcher.js'
export { Coordinator } from './loop/coordinator.js'
export type { CoordinatorDeps } from './loop/coordinator.js'
export { onTestFailure, reactiveMode } from './loop/reactive.js'
export type { ReactiveMode, ReactiveDeps, ReactiveOutcome, BreakerConfig } from './loop/reactive.js'
export { handleTestSignal, handleGitSignal } from './watchers/handler.js'
export type { TestHandleResult } from './watchers/handler.js'
export { parseVitestJson, readVitestResultFile } from './watchers/testWatcher.js'
export type { VitestJson, RunMeta } from './watchers/testWatcher.js'
export { commitSignal, branchSignal, readGitHead } from './watchers/gitWatcher.js'
export type { TestSignal, GitSignal, WatchSignal } from './watchers/types.js'
export { notifyForces, describeNotify } from './notify/ntfy.js'
export type { NotifyInput, NotifyResult, NotifyOptions } from './notify/ntfy.js'
export { runMigrations } from './db/migrate.js'
export { query, withTransaction, closePool, pool } from './db/pool.js'
export { env, parseDbUrl } from './env.js'
export type * from './core/types.js'
